library(syuzhet)
library(lubridate)
library(ggplot2)
library(scales)
library(reshape2)
library(dplyr)
library(fmsb)
data <- read.csv('Final_script.csv')
data <- data %>% filter(Speaker == "Harry")
Dialogue<- iconv(data$Sentence)
s <- get_nrc_sentiment(Dialogue)
head(s)
colSums(s)
df <- as.data.frame(colSums(s))
df <- as.data.frame(t(df))
df <- rbind(rep(60,10),rep(10,20), df)
radarchart(df,pcol='black',pfcol='grey',plwd=2,cglcol="black" ,cglwd=0.8)

data <- read.csv('Final_script.csv')
data <- data %>% filter(Speaker == "McGonagall")
Dialogue<- iconv(data$Sentence)
s <- get_nrc_sentiment(Dialogue)
head(s)
colSums(s)
df <- as.data.frame(colSums(s))
df <- as.data.frame(t(df))
df <- rbind(rep(28,4),rep(4,10), df)
df
radarchart(df,pcol='black',plwd=2,cglcol="black" ,cglwd=0.8,pdensity=c(0, 1, 2))

